workflows:
  eth_ios_build:
    name: ETH Zeiterfassung iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: 🔧 Vorbereitung
        script: |
          flutter clean
          flutter pub get
      - name: 📱 iOS Unsigned Build
        script: |
          flutter build ipa --release --no-codesign
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
    artifacts:
      - Runner.ipa
    publishing:
      email:
        recipients:
          - maik.frankenberger94@web.de   # <--- Hier deine E-Mail eintragen, um den Download-Link zu bekommen